export { default as sidebarAlgorithm } from './algorithm'
export { default as exeryWeek } from './exeryweek'
export { default as sidebarInterview } from './interview'
export { default as sidebarPartterns } from './partterns'
export { default as sidebarProgram } from './program'
