name: Contributors

on:
  schedule:
    - cron: '0 14 * * 0' # At 01:00 on Sunday.
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  contributors:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: wow-actions/contributors-list@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          svgPath: CONTRIBUTORS.svg
          round: true